config/routes.rb
BuilderApp::Application.routes.draw do
  
  resources :quiz_categories do
    collection { post :import }
  end
  resources :quiz_questions
root 'dashboard#index'     
  get "api_help/index"
  resources :users
  devise_for :admins, path_names: {:sign_in => 'login', :sign_up => 'register', :sign_out => 'logout'},:controllers => {:sessions=>"admins/sessions",:passwords => "admins/passwords"}
  devise_for :users,path_names: {:sign_in => 'login'}

  #get "properties/document_category/:id" => "properties#document_category",:as =>:document_category
 


  #end
  namespace :api,:defaults => {:format => 'json'} do
    scope :module => :v1 do
      post 'signup' => 'registrations#create',:as=>:signup
      post 'login'  => 'sessions#create',:as => :end_user_login
      get  'logout' => 'sessions#destroy',     :as => :end_user_logout
      post 'forgot_password' => 'passwords#create'
      post 'change_password' => 'passwords#change_password'
      get  'fetch_question' => 'quiz_questions#fetch_question'
      get  'fetch_question_pro' => 'quiz_questions#fetch_question_paid_app'
      get  'question_by_category' => 'quiz_questions#question_by_category'
      get  'list_categories' => 'quiz_categories#list_categories'
      get  'questions_by_multiple_category' => 'quiz_questions#questions_by_multiple_category'
      get  'question_for_quick_session' => 'quiz_questions#question_for_quick_session'
      post 'global_avarage_for_questions' => 'quiz_questions#global_avarage_for_questions'
      post  'challenge/create'   => 'challenges#create'
      get   'challenge/sent_challenges_list' => 'challenges#sent_challenges_list'
      get   'challenge/recived_challenges_list' => 'challenges#recived_challenges_list'
      get   'challenge/show' => 'challenges#show'
      post  'challenge/won_lost' => 'challenges#won_lost'
      get  'challenge/challenge_statistics' => 'challenges#won_lost_statstics'
      post 'challenge/accept' => 'challenges#accept'
     end
  end

end

app/models/quiz_question.rb
class QuizQuestion < ActiveRecord::Base

	##Paperclip##
	has_attached_file :question_image,:url => "/system/question_images/:attachment/:id_partition/:style/:filename",:styles => {:thumb => "50x50>",:large => "200x200>" ,:small => "100x100>"}
	has_attached_file :answer_image,:url => "/system/answer_images/:attachment/:id_partition/:style/:filename",:styles => {:thumb => "50x50>",:large => "200x200>" ,:small => "100x100>"}
	
	##Association##
	belongs_to :quiz_category
	has_many   :quiz_question_options

	##Validations##
	#validates :question_or_question_image,:correct_answer_or_answer_image,:presence => true
	validates_attachment_content_type :question_image, :content_type => /\Aimage\/.*\Z/
	validates_attachment_content_type :answer_image, :content_type => /\Aimage\/.*\Z/

	
	accepts_nested_attributes_for :quiz_question_options, :allow_destroy => true

	## scopes##
	scope  :random, lambda {{:order=>'RAND()' } }
	scope  :is_free,->{where(is_demo: true)}
	scope  :is_paid,->{where(is_demo: false)}
	#scope  :random, lambda {{:order=>'RANDOM()' } }
	scope  :by_category,lambda{|quiz_category_id|where(["quiz_category_id IN (?)",quiz_category_id])}
    scope  :by_id,lambda{|question_id|where(["id IN (?)",question_id])}

	def answer_options
		self.quiz_question_options
	end

	def question_url
	    HOST_NAME + self.question_image.url
	end

	def answer_url
		HOST_NAME + self.answer_image.url
	end

	private

  ## Custom Validation Method ##
	def question_or_question_image
		if question.blank? && question_image.blank?
			self.errors.add :question, "can blank only if image for question is present (either set text for question or image)"
		end
	end

	def correct_answer_or_answer_image
		if correct_answer.blank? && answer_image.blank?
			self.errors.add :correct_answer,"can blank only if image for answewr is present (either set text for answer or image)"
		end 
	end
end

app/controllers/api/v1/quiz_questions_controller.rb
class Api::V1::QuizQuestionsController < Api::V1::ApplicationController
	before_filter :authentication_user_with_authentication_token

  #this fetch random questions category wise
  def fetch_question
  	@question  = QuizQuestion.random.is_free.includes(:quiz_question_options,:quiz_category)
    @questions = @question.group_by &:quiz_category_id
  end
  
  def fetch_question_paid_app
    @question  = QuizQuestion.random.is_paid.includes(:quiz_question_options,:quiz_category)
    @questions = @question.group_by &:quiz_category_id    
  end

  #select questions based on category
  def question_by_category
  	if params[:id].present?
  		@questions = QuizQuestion.where(quiz_category_id: params[:id]).includes(:quiz_question_options,:quiz_category)
  	else
      render_json({:errors => "Id is required", :status => 404}.to_json)
    end
  end

  #select questions based on multiple categories

  def questions_by_multiple_category
    if params[:ids].present? && params[:is_free].present? && params[:num].present?
      @category_ids = params[:ids].split(/,\s*/)
      if @category_ids.length > params[:num].to_i
        @category_ids = @category_ids[0..(params[:num].to_i-1)]
      end
      if params[:is_free] == "1"
        @question  = QuizQuestion.random.by_category(@category_ids).is_free.includes(:quiz_question_options,:quiz_category)
        @question.update_all("attempted = attempted + 1")
        @questions = @question.group_by &:quiz_category_id
      else
        @question  = QuizQuestion.random.by_category(@category_ids).is_paid.includes(:quiz_question_options,:quiz_category)
        @questions = @question.group_by &:quiz_category_id
      end
      @category_numbers = Hash.new
      sum = 0
      total = @question.length > params[:num].to_i ? params[:num].to_i : @question.length
      category_length = @category_ids.length
      while sum <= total do
        diff = total - sum
        number = diff / category_length
        @category_ids.each do |category|
          counter = @category_numbers[category.to_i].present? ? @category_numbers[category.to_i]+number : number
          if @questions[category.to_i].length >= counter
            @category_numbers[category.to_i] = counter
          else
            @category_numbers[category.to_i] = @questions[category.to_i].length
            category_length = category_length - 1
          end
          sum = sum + @category_numbers[category.to_i]
        end
      end
    else
      render_json({:errors => "Required field missing", :status => 404}.to_json)
    end
  end
    
  def question_for_quick_session
   	@questions  = QuizQuestion.random.limit(50).includes(:quiz_question_options,:quiz_category)
   	#@question.update_all("attempted = attempted + 1")
   	#@questions = @question.group_by &:quiz_category_id
  end
    
  def global_avarage_for_questions
    if params[:questions_id].present? && params[:answers_id].present?
      @questions_ids = params[:questions_id].split(/,\s*/)
      @answers_ids = params[:answers_id].split(/,\s*/)
      @questions = QuizQuestion.by_id(@questions_ids).includes(:quiz_question_options,:quiz_category)
      @questions.each_with_index do |key,value|
        @quiz_question = QuizQuestion.find(key)
        if @quiz_question.correct_answer==@answers_ids[value]
          @quiz_question.update_attribute(:correct_answer_count,@quiz_question.correct_answer_count + 1)             
        end
      end
    else
      render_json({:errors => "Required field missing", :status => 404}.to_json)
    end   
  end
end

app/controllers/quiz_questions_controller.rb
class QuizQuestionsController < ApplicationController
  before_action :set_quiz_question, only: [:show, :edit, :update, :destroy]
  add_breadcrumb 'Questions', :quiz_questions_path
  add_breadcrumb 'Create a new Question', '', :only => [:new, :create]
  add_breadcrumb 'Edit a Question', '', :only => [:edit, :update]
  add_breadcrumb 'Question', '', :only => [:show]

  # GET /quiz_questions
  def index
    @quiz_questions = QuizQuestion.page(params[:page]).per(10)
  end

  # GET /quiz_questions/1
  def show
  end

  # GET /quiz_questions/new
  def new
    @quiz_question = QuizQuestion.new
    @quiz_question.quiz_question_options.build
    @category_name = nil
    @category      = QuizCategory.where(is_image: true)
  end

  # GET /quiz_questions/1/edit
  def edit
    @category_name = @quiz_question.quiz_category.is_image
  end

  # POST /quiz_questions
  def create
    @quiz_question = QuizQuestion.new(quiz_question_params)
    if @quiz_question.save
      redirect_to @quiz_question, notice: 'Quiz question was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /quiz_questions/1
  def update
    if @quiz_question.update(quiz_question_params)
      redirect_to @quiz_question, notice: 'Quiz question was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /quiz_questions/1
  def destroy
    @quiz_question.destroy
    redirect_to quiz_questions_url, notice: 'Quiz question was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz_question
      @quiz_question = QuizQuestion.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def quiz_question_params
      params.require(:quiz_question).permit(:question,:quiz_category_id,:correct_answer,:description,:is_demo,:question_image,:answer_image,quiz_question_options_attributes:[:name,:id,:_destroy,:answer])
    end
end

app/views/quiz_questions/_form.html.erb
<%= semantic_nested_form_for(@quiz_question,:html => {:class=>"span12 form-horizontal widget stacked dark"}) do |f| %>
<header>
<h4 class="title">Question</h4>
</header>
<section class="body">
  <div class="body-inner">
    <div class="control-group">
      <%= f.label :quiz_category_id,"Category",:class => "control-label" %>
       <div class="controls">
        <%=f.collection_select :quiz_category_id,QuizCategory.all,:id,:name ,{},{:class => "large m-wrap"} %>
        <div class="inline-errors"><%= show_inline_errors(f.object.errors,["quiz_category_id"])%></div>
      </div>
    </div>
    <div class="control-group" id="question_text" style="display: <%= (@category_name != true)? 'block' : 'none' %>;">
      <%= f.label :question,:class => "control-label" %>
       <div class="controls">
        <%= f.text_field :question ,:class => "m-wrap large" ,:placeholder => "Question"%><div class="inline-errors"><%= show_inline_errors(f.object.errors,["question"])%></div>
      </div>
    </div>
    <div class="control-group" id="answer_text" style="display: <%= (@category_name != true)? 'block' : 'none' %>;">
      <%= f.label :correct_answer,:class => "control-label" %>
      <div class="controls">
        <%= f.text_field :correct_answer ,:class => "m-wrap large" ,:placeholder => "Correct Answer"%><div class="inline-errors"><%= show_inline_errors(f.object.errors,["correct_answer"])%></div>
      </div>
    </div>

    <div class="control-group" id="question_image" style="display: <%= (@category_name == true)? 'block' : 'none' %>;">
      <%= f.label :question_image, "Question Image",:class => "control-label" %>
      <div class="controls">
        <%= f.file_field :question_image ,:class => "m-wrap large" %>
        <%= image_tag f.object.question_image.url(:thumb) if f.object.question_image.present? %>
      </div>
    </div>

    <div class="control-group" id="answer_image" style="display: <%= (@category_name == true)? 'block' : 'none' %>;">
      <%= f.label :answer_image, "Correct Answer Image",:class => "control-label" %>
      <div class="controls">
        <%= f.file_field :answer_image ,:class => "m-wrap large" %>
        <%= image_tag f.object.answer_image.url(:thumb) if f.object.answer_image.present? %>
      </div>
    </div>

    <div class="control-group" >
      <%= f.label :is_demo,"Is Free Version?",:class => "control-label" %>
      <div class="controls">
        <%= f.check_box :is_demo ,:class => "m-wrap large"%>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :description,:class => "control-label" %>
       <div class="controls">
        <%= f.text_field :description ,:class => "m-wrap large" ,:placeholder => "Description" %><div class="inline-errors"><%= show_inline_errors(f.object.errors,["description"])%></div>
      </div>
    </div>
    <fieldset>
      <legend>Answers</legend>
      <div class="control-group">
        <label class="control-label">Add Answer Options</label>
        <%= f.inputs do%>        
          <%= f.semantic_fields_for :quiz_question_options %>
          <%= f.link_to_add "Add More Option",:quiz_question_options,:class =>"" %>
        <% end %>
      </div>
    </fieldset>
  </div>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary"><i class="icon-ok"></i> Save</button>
    <%= link_to "Cancel", quiz_questions_path, :class => "btn" %>
  </div>
 </section>
<% end %>
<script type="text/javascript">
  $('#quiz_question_quiz_category_id').change(function(){
    var category = $("#quiz_question_quiz_category_id option:selected").text();
    if(category == "Visual Logic" || category == "Visual logic" || category == "Symbols" || category == "Spacial reasoning" || category == "Spacial Reasoning" || category == "Syllogism" ){
      $('#question_image').show();
      $('#answer_image').show();
      $('#option_image').show();
      $('#question_text').hide();
      $('#answer_text').hide();
      $('#option_text').hide();
    }
    else{
      $('#question_image').hide();
      $('#answer_image').hide();
      $('#option_image').hide();
      $('#question_text').show();
      $('#answer_text').show();
      $('#option_text').show();
    }
  });
</script>

app/views/quiz_questions/_quiz_question_option_fields.html.erb
<div id="option_text" style="display: <%= (@category_name != true)? 'block' : 'none' %>;">
	<%= f.input :name,:label => false ,:input_html =>{:class => "m-wrap large"},:placeholder => "Answer" %>
	<%= f.link_to_remove "Remove this Answer",:class =>""%>
<br>
</div>
<div id="option_image" style="display: <%= (@category_name == true)? 'block' : 'none' %>;" >
	<%= f.file_field :answer ,:class => "m-wrap large" %>
	<%= image_tag f.object.answer.url(:thumb) if f.object.answer.present? %>
	<%= f.link_to_remove "Remove this Answer",:class =>""%>
</div>

app/views/quiz_questions/edit.html.erb
<%= render 'form' %>

app/views/quiz_questions/index.html.erb
<div class="row-fluid">
<!-- START Basic Table -->
  <div class="span12 widget dark stacked">
    <header>
      <h4 class="title">Question</h4>
        <!--/ END Toolbar -->
    </header>
    <section class="body">
      <div class="body-inner no-padding">
        <% if @quiz_questions.present? %>
          <table class="table">
            <thead>
              <tr>
                <th>Question</th>
                <th>Correct Answer</th>
                <th>Description</th>
                <th colspan=2>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @quiz_questions.each do |quiz_question| %>
                <tr>
                  <td><% if quiz_question.question_image.present?%>
                      <%= image_tag quiz_question.question_image.url(:thumb)%>
                      <% else %>
                      <%= quiz_question.question%>
                      <% end %>
                  </td>
                  <td><% if quiz_question.question_image.present?%>
                      <%= image_tag quiz_question.answer_image.url(:thumb)%>
                      <% else %>
                      <%= quiz_question.correct_answer%>
                      <% end %>
                  </td>
                  <td><%= quiz_question.description%></td>
                  <td><%= view_link(quiz_question_path(quiz_question)) %>
                  <%= edit_link(edit_quiz_question_path(quiz_question)) %>
                  <%= delete_link(quiz_question_path(quiz_question))%></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @quiz_questions , :theme => 'my_custom_theme' %>
        <% else %>
          <strong>Questions Not Present!</strong>
        <% end %>
      </div>
    </section>
  </div>
</div>
<br>
<%= add_link('New Quiz question', new_quiz_question_path)%>

app/views/quiz_questions/new.html.erb
<%= render 'form' %>

app/views/quiz_questions/show.html.erb
<div class="row-fluid">
<!-- START Basic Table -->
  <div class="span12 widget dark stacked">
    <header>
      <h4 class="title">Question</h4>
        <!--/ END Toolbar -->
    </header>
    <section class="body">
      <div class="body-inner no-padding">
        <table class="table">
          <tr>
          	<td><strong>Question:</strong></td>
          	<td>
          		<% if @quiz_question.question_image.present?%>
                    <%= image_tag @quiz_question.question_image.url(:small)%>
                    <% else %>
                    <%= @quiz_question.question%>
                    <% end %>
            </td>
          </tr>
          <tr>
          	<td><strong>Correct Answer:</strong></td>
          	<td>
          		<% if @quiz_question.answer_image.present?%>
                    <%= image_tag @quiz_question.answer_image.url(:small)%>
                    <% else %>
                    <%= @quiz_question.correct_answer%>
                    <% end %>
          	</td>
          </tr>
          <tr>
          	<td><strong>Description:</strong></td>
          	<td><%= @quiz_question.description%></td>
          </tr>
          <tr>
          	<td><strong>Answer Options</strong></td>
          	<td>
          		<ul>
          			<% @quiz_question.quiz_question_options.each do |options| %>
          				<li>
          					<% if options.answer.present?%>
                    <%= image_tag options.answer.url(:small)%>
                    <% else %>
                    <%= options.name%>
                    <% end %>
          				</li>
          			<% end %>
          		</ul>
          	</td>
          </tr>
          <tr>
          	<td><strong>Version:</strong></td>
          	<td><%= @quiz_question.is_demo==true ? "Free" : "Pro"%></td>
          </tr>
        </table>
      </div>
    </section>
  </div>
  <%= edit_link(edit_quiz_question_path(@quiz_question),'btn blue') %>    
</div>