config/routes.rb
BuilderApp::Application.routes.draw do
  
  resources :quiz_categories do
    collection { post :import }
  end
  resources :quiz_questions
root 'dashboard#index'     
  get "api_help/index"
  resources :users
  devise_for :admins, path_names: {:sign_in => 'login', :sign_up => 'register', :sign_out => 'logout'},:controllers => {:sessions=>"admins/sessions",:passwords => "admins/passwords"}
  devise_for :users,path_names: {:sign_in => 'login'}

  #get "properties/document_category/:id" => "properties#document_category",:as =>:document_category
 


  #end
  namespace :api,:defaults => {:format => 'json'} do
    scope :module => :v1 do
      post 'signup' => 'registrations#create',:as=>:signup
      post 'login'  => 'sessions#create',:as => :end_user_login
      get  'logout' => 'sessions#destroy',     :as => :end_user_logout
      post 'forgot_password' => 'passwords#create'
      post 'change_password' => 'passwords#change_password'
      get  'fetch_question' => 'quiz_questions#fetch_question'
      get  'fetch_question_pro' => 'quiz_questions#fetch_question_paid_app'
      get  'question_by_category' => 'quiz_questions#question_by_category'
      get  'list_categories' => 'quiz_categories#list_categories'
      get  'questions_by_multiple_category' => 'quiz_questions#questions_by_multiple_category'
      get  'question_for_quick_session' => 'quiz_questions#question_for_quick_session'
      post 'global_avarage_for_questions' => 'quiz_questions#global_avarage_for_questions'
      post  'challenge/create'   => 'challenges#create'
      get   'challenge/sent_challenges_list' => 'challenges#sent_challenges_list'
      get   'challenge/recived_challenges_list' => 'challenges#recived_challenges_list'
      get   'challenge/show' => 'challenges#show'
      post  'challenge/won_lost' => 'challenges#won_lost'
      get  'challenge/challenge_statistics' => 'challenges#won_lost_statstics'
      post 'challenge/accept' => 'challenges#accept'
     end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
include SendPush
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ##Associations## 
  has_many :authentication_tokens, :dependent => :destroy
  has_many :sent_challenges,:dependent => :destroy,:class_name => 'Challenge'
  has_many :challenge_details, through: :sent_challenges
  has_many :recived_challenges_details,:dependent => :destroy,:class_name => 'ChallengeDetail',:foreign_key => "reciver_id"
  
  ##Validations##
  #validates :city,:state,:phonenumber,:presence => true
  validates :firstname,:lastname,:presence => true,:format => {:with => /^[a-zA-z]+$/,:multiline => true,:message => "Only text is Allowed" }
  #validates_format_of :phonenumber, 
                      #:with => /\A[0-9]{10}\Z/,:length=>10

  ##scopes                    
  scope :get_user_device_ids,lambda { |device_id| where("device_id = ?", device_id) }
  scope :without_user, lambda{|user| where (user ? ["id != ?", user.id] : {}) }

  class << self
    def authenticate_user_with_auth(email, password)
      return nil unless email.present? or password.present?
      u = User.find_by_email(email)
      (u.present? && u.valid_password?(password))? u : nil
    end

    def invalid_credential
      "Email or Password is not valid"
    end
    def invalid_credentials
      "Email is required"
    end
  end

  def fullname
    "#{firstname} #{lastname}"
  end

  def has_android_device?
    device_type.downcase == "android"
  end

  def has_iphone_device?
    device_type.downcase == "iphone"
  end
  
  def check_duplicate_device_ids(device_id,user,device_type)
    @users=User.without_user(user).get_user_device_ids(device_id)
    if @users.present?
      @users.update_all({:device_id => nil})
    end
    user.device_id = device_id
    user.device_type = device_type
    user.save
  end
  
  def send_challenge_friend(msg)
		if self.device_id?
      if self.has_android_device?
       
        GCM.send_notification(self.device_id, {:message => msg}, :collapse_key => "Challenge", :time_to_live => 3600)
         puts "android"
      elsif self.has_iphone_device?	        
       
        APNS.send_notification(self.device_id, :alert => msg, :badge => 1, :sound => 'default')	              
        puts "iphone"
      end
    end
	end

  def display_errors
    self.errors.full_messages.join(', ')
  end

  def recived_challenges
    accepted = Challenge.where(id: self.recived_challenges_details.with_status("accepted").pluck("challenge_id").uniq).includes(:challenge_details,:sender)
    pending = Challenge.where(id: self.recived_challenges_details.with_status("pending").pluck("challenge_id").uniq).includes(:challenge_details,:sender)
    pending + accepted
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  add_breadcrumb 'Users', :users_path
  add_breadcrumb 'Create a new User', '', :only => [:new, :create]
  add_breadcrumb 'Edit a User', '', :only => [:edit, :update]
  # GET /users
  # GET /users.json
  def index
    @users = User.page(params[:page]).per(10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email,:password,:password_confirmation,:firstname, :lastname, :address, :city, :state, :country, :phonenumber)
    end
end

app/views/users/_form.html.erb
<%= semantic_nested_form_for(@user,:html => {:class=>"span12 form-horizontal widget stacked dark"}) do |f| %>
<header>
<h4 class="title">User</h4>
</header>
<section class="body">
<div class="body-inner">
  <div class="control-group">
    <%= f.label :email,:class => "control-label" %>
     <div class="controls">
      <%= f.text_field :email ,:class => "m-wrap large" ,:placeholder => "Name"%><div class="inline-errors"><%= show_inline_errors(f.object.errors,["email"])%></div>
    </div>
  </div>
  <div class="control-group" >
    <%= f.label :password,:class => "control-label" %>
    <div class="controls">
      <%= f.password_field :password ,:class => "m-wrap large" ,:placeholder => "Password"%><div class="inline-errors"><%= show_inline_errors(f.object.errors,["password"])%></div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation,:class => "control-label" %>
     <div class="controls">
      <%= f.password_field :password_confirmation ,:class => "m-wrap large" ,:placeholder => "Password Confirmation" %><div class="inline-errors"><%= show_inline_errors(f.object.errors,["password_confirmation"])%></div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :firstname,:class => "control-label" %>
    <div class="controls">
      <%= f.text_field :firstname ,:class => "m-wrap large" ,:placeholder => "First Name"%><div class="inline-errors"><%= show_inline_errors(f.object.errors,["firstname"])%></div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lastname,:class => "control-label" %>
     <div class="controls">
      <%= f.text_field :lastname ,:class => "m-wrap large" ,:placeholder => "Last Name"%><div class="inline-errors"><%= show_inline_errors(f.object.errors,["lastname"])%></div>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :city,:class => "control-label" %>
    <div class="controls">
      <%= f.text_field :city ,:class => "m-wrap large" ,:placeholder => "City"%><div class="inline-errors"><%= show_inline_errors(f.object.errors,["city"])%></div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state,:class => "control-label" %>
    <div class="controls">
      <%= f.text_field :state ,:class => "m-wrap large" ,:placeholder => "State"%><div class="inline-errors"><%= show_inline_errors(f.object.errors,["state"])%></div>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :phonenumber,:class => "control-label" %>
    <div class="controls">
      <%= f.text_field :phonenumber ,:class => "m-wrap large" ,:placeholder => "Phone Number"%><div class="inline-errors"><%= show_inline_errors(f.object.errors,["phonenumber"])%></div>
    </div>
  </div>
  </div>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary"><i class="icon-ok"></i> Save</button>
    <%= link_to "Cancel", users_path, :class => "btn" %>
  </div>
 </section>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>
<%#= view_link(user_path(@user)) %>

app/views/users/index.html.erb
<div class="row-fluid">
<!-- START Basic Table -->
<div class="span12 widget dark stacked">
  <header>
      <h4 class="title">Users</h4>
      <!--/ END Toolbar -->
  </header>
  <section class="body">
    <div class="body-inner no-padding">
      <% if @users.present? %>
        <table class="table">
          <thead>
            <tr>
              <th>Email</th>
              <th>Firstname</th>
              <th>Lastname</th>
              
              <th>Country</th>
              <th colspan=2>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><span><%= user.email %></span></td>
                <td><span><%= user.firstname %></span></td>
                <td><span><%= user.lastname %></span></td>
           
                <td><span><%= user.country %></span></td>
            
                <td>
                  <%#= view_link(user_path(user)) %>
                  <%= edit_link(edit_user_path(user)) %>
                  <%= delete_link(user_path(user)) %>
                </td>
              </tr>
            <%end%>
          </tbody>
        </table>
        <%= paginate @users , :theme => 'my_custom_theme' %>
      <% else %>
        <strong>Users Not Present!</strong>
      <% end %>
      </div>
  </section>
</div>
<!--/ END Striped Table -->
<!--/ END Row -->
<%= add_link('New User',new_user_path) %>

app/views/users/new.html.erb
<%= render 'form' %>
   