config/routes.rb
BuilderApp::Application.routes.draw do
  
  resources :quiz_categories do
    collection { post :import }
  end
  resources :quiz_questions
root 'dashboard#index'     
  get "api_help/index"
  resources :users
  devise_for :admins, path_names: {:sign_in => 'login', :sign_up => 'register', :sign_out => 'logout'},:controllers => {:sessions=>"admins/sessions",:passwords => "admins/passwords"}
  devise_for :users,path_names: {:sign_in => 'login'}

  #get "properties/document_category/:id" => "properties#document_category",:as =>:document_category
 


  #end
  namespace :api,:defaults => {:format => 'json'} do
    scope :module => :v1 do
      post 'signup' => 'registrations#create',:as=>:signup
      post 'login'  => 'sessions#create',:as => :end_user_login
      get  'logout' => 'sessions#destroy',     :as => :end_user_logout
      post 'forgot_password' => 'passwords#create'
      post 'change_password' => 'passwords#change_password'
      get  'fetch_question' => 'quiz_questions#fetch_question'
      get  'fetch_question_pro' => 'quiz_questions#fetch_question_paid_app'
      get  'question_by_category' => 'quiz_questions#question_by_category'
      get  'list_categories' => 'quiz_categories#list_categories'
      get  'questions_by_multiple_category' => 'quiz_questions#questions_by_multiple_category'
      get  'question_for_quick_session' => 'quiz_questions#question_for_quick_session'
      post 'global_avarage_for_questions' => 'quiz_questions#global_avarage_for_questions'
      post  'challenge/create'   => 'challenges#create'
      get   'challenge/sent_challenges_list' => 'challenges#sent_challenges_list'
      get   'challenge/recived_challenges_list' => 'challenges#recived_challenges_list'
      get   'challenge/show' => 'challenges#show'
      post  'challenge/won_lost' => 'challenges#won_lost'
      get  'challenge/challenge_statistics' => 'challenges#won_lost_statstics'
      post 'challenge/accept' => 'challenges#accept'
     end
  end

end

app/views/layouts/_footer.html.erb
<!-- BEGIN FOOTER -->
<div class="footer">
  <div class="footer-inner">
		2013 &copy; IQTrainerApp
	</div>
	<div class="footer-tools">
		<span class="go-top">
		  <i class="icon-angle-up"></i>
		</span>
	</div>
</div>
	<!-- END FOOTER -->

app/views/layouts/_page_sidebar.html.erb
<!-- BEGIN EMPTY PAGE SIDEBAR -->
  <div class="page-sidebar nav-collapse collapse visible-phone visible-tablet">
    <ul class="page-sidebar-menu">
      <li class="<%= 'active' if controller.controller_name == 'dashboard' %>">
        <a href='<%= root_path %>'>
          Dashboard                        
        </a>
      </li>
      <li class="<%= 'active' if controller.controller_name == 'users' %>">
        <a href='<%=users_path%>'>Users</a>
      </li>

      <li class="<%= 'active' if controller.controller_name == 'quiz_categories' %>">
        <a href='<%=quiz_categories_path%>'>
          Properties
        </a>
      </li>

      <li class="<%= 'active' if controller.controller_name == 'quiz_questions' %>">
        <a href='<%=quiz_questions_path%>'>
          Properties
        </a>
      </li>
      
    </ul>
  </div>
<!-- END EMPTY PAGE SIDEBAR -->

app/views/layouts/_sidebar_menu.html.erb
   <aside id="sidebar">
                <!-- START Sidebar Content -->
                <div class="sidebar-content">
                    <!-- START Sidebar Tab -->

                    <!-- START Tab Content -->
                    <div class="tab-content">
                        <!-- START Tab Pane(menu) -->
                        <div class="tab-pane active" id="tab-menu">
                            <!-- START Sidebar Menu -->
                            <nav id="nav" class="accordion">
                                <ul id="navigation">
                                    <!-- START Menu Divider -->
                                    <li class="divider">Main Menu</li>
                                    <!--/ END Menu Divider -->

                                    <!-- START Menu -->
                                    <li class="accordion-group ">
                                        <a href="<%=root_path%>">
                                            <span class="icon icone-dashboard"></span>
                                            <span class="text">Dashboard</span>
 
                                        </a>
                                    </li>
                                    <!--/ END Menu -->

                                    <!-- START Menu -->
                                    
                                    <!--/ END Menu -->

                                    <!-- START Menu -->
                                    <li class="accordion-group ">
                                        <a href="<%= users_path %>">
                                            <span class="icon icone-user"></span>
                                            <span class="text">Users</span>
                                         
                                        </a>
                                        
                                    </li>
                                     <li class="accordion-group ">
                                        <a href="<%= quiz_categories_path%>">
                                            <span class="icon icone-folder-close"></span>
                                            <span class="text">Categories</span>
                                         
                                        </a>
                                        
                                    </li>
                                    <li class="accordion-group ">
                                        <a href="<%= quiz_questions_path%>">
                                            <span class="icon icone-folder-close"></span>
                                            <span class="text">Questions</span>
                                         
                                        </a>
                                        
                                    </li>
                                  
                                    <!--/ END Menu -->

                                    <!-- START Menu -->
                                    
                        </div>
                        <!--/ END Tab Pane(overview) -->
                    </div>
                    <!--/ END Tab Content -->
                </div>
                <!--/ END Sidebar Content -->
            </aside>

app/views/layouts/_top_header.html.erb
 <header id="header">
                <!-- START Logo -->
                <div class="logo hidden-phone hidden-tablet">
                    <a href="<%= root_path %>"><img src="/assets/logo.png" alt="" style="width: 181px;height: 51px;"></a>
                    <small class="version"></small>
                </div>
                <!--/ END Logo -->

                <!-- START Mobile Sidebar Toggler -->
                <a href="<%= root_path %>" class="toggler" data-toggle="sidebar"><span class="icon icone-reorder"></span></a>
                <!--/ END Mobile Sidebar Toggler -->

                <!-- START Toolbar -->
                <ul class="toolbar" id="toolbar">
                    


                    <!-- START Profile -->
                    <li class="profile">
                        <a href="#" data-toggle="dropdown">
                            <span class="avatar"><img src="" alt=""></span>
                            <span class="text hidden-phone"><%= Admin.first.email%><span class="role">Admin</span></span>
                            <span class="arrow icone-caret-down"></span>
                        </a>
                        <!-- START Dropdown Menu -->
                        <div class="dropdown-menu" role="menu">
                            <header>
                                Your Profile 
                            </header>
                            <ul class="body">
                                <li>
                                    <a href="<%= edit_admin_registration_path%>"><i class="icon-tasks"></i> Change Password</a>
                                </li>
                      
                       
                            </ul>
                            <footer>
                                <a href="<%= destroy_admin_session_path%>" class="text" data-method='delete'><span class="icon icone-off"></span> Sign Off</a>
                            </footer>
                        </div>
                        <!--/ END Dropdown Menu -->
                    </li>
                    <!--/ END Profile -->
                </ul>
                <!--/ END Toolbar -->
            </header>

app/views/layouts/api_help.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IQtrainer app</title>
    <%= stylesheet_link_tag    "api_help", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "api_help", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="content">
      <%= yield %>
    </div>  
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IQtrainer app</title>
    <%= stylesheet_link_tag    "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  <script>
    jQuery(document).ready(function() {    
       App.init();
    });
  </script>
    
  </head>
  
  <body class="page-header-fixed page-full-width">
    <%= render :partial => "layouts/top_header" %>
   
    
    <!-- BEGIN CONTAINER -->   
    <div class="page-container row-fluid" >
     <%= render :partial => "layouts/sidebar_menu" %>
    <!-- BEGIN PAGE -->
     <section id="main">
                <!-- START Bootstrap Navbar -->
                <div class="navbar navbar-static-top">
                    <div class="navbar-inner">
                        <!-- Breadcrumb -->
                        <ul class="breadcrumb">
              <li>
                <%=breadcrumbs%>
              </li>
              </ul>
              <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
          </div>
          <!-- END PAGE HEADER-->
          <!-- BEGIN PAGE CONTENT-->
          <div class="container-fluid">
                    <!-- START Row -->
                    <div class="row-fluid">
              <% flash.each do |key, message| %>
                <div id="flash_<%= key %>" class="alert"><%= message %></div>
              <% end %>
              <%= yield %>
            </div>
          </div>
          <!-- END PAGE CONTENT-->
        </div>
        <!-- END PAGE CONTAINER--> 
      </div>
      <!-- END PAGE -->    
    </div>
    <!-- END CONTAINER --> 
    <%= yield :scripts %>   
    <%= render :partial => "layouts/footer" %>
    </div>
    </div>
  </body>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IQtrainer app</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application"  %>
    <%= csrf_meta_tags %>
  </head>
   <div id="wrapper">
    <!-- START Template Canvas -->
    <div id="canvas">
      <!-- START Themer -->
      <!-- You can remove this. For demo purpose only -->
      <div class="container-fluid">
        <!-- START Row -->
        <div class="row-fluid">
          <!-- START Login Widget Form -->
          <link rel="shortcut icon" href="/favicon.ico" />
          <p>&nbsp;</p>
          <% flash.each do |key, message| %>
            <div id="flash_<%= key %>" class="alert"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
    </div>
  </div>
</div>
  </body>
</html>